# Generated by Django 5.0.2 on 2024-02-22 17:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='data_modificacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='valor',
            field=models.FloatField(),
        ),
    ]
